# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOwnToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name=b'Key')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
