# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kapas', '0002_myowntoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Which_location', models.CharField(blank=True, max_length=20)),
                ('Block_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Site_type', models.PositiveIntegerField(choices=[(0, b'Normal_Block'), (1, b'Common_Block'), (2, b'warehouse')], default=0)),
                ('Associated_floor', models.CharField(blank=True, max_length=5, null=True)),
                ('Power_status', models.PositiveIntegerField(choices=[(0, b'OFF'), (1, b'ON')], default=1)),
                ('Total_No_Of_Block', models.PositiveIntegerField(default=0)),
                ('Total_No_Of_Aisle', models.PositiveIntegerField(default=0)),
                ('Total_No_ofRow', models.PositiveIntegerField(default=0)),
                ('Total_Lights', models.PositiveIntegerField(default=0)),
                ('Cumulative_units', models.FloatField(default=0)),
                ('saved_Units', models.FloatField(default=0)),
                ('Shared_Cumulative', models.FloatField(default=0)),
                ('Baseline_units', models.FloatField(default=0)),
                ('Contact_Number', models.CharField(blank=True, max_length=10, null=True)),
                ('Live_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Unit_Rate_Utility', models.FloatField(default=0)),
                ('Power_Backup_Rate_Utility', models.FloatField(default=0)),
                ('Percentage_Saved_Energy', models.FloatField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='kapas.Customer')),
            ],
        ),
        migrations.DeleteModel(
            name='MyOwnToken',
        ),
    ]
