# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kapas', '0003_auto_20190319_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaveEnergy', models.FloatField(blank=True, default=0, null=True)),
                ('Percentage_Saved', models.FloatField(blank=True, default=0, null=True)),
                ('unit_consumption', models.FloatField(blank=True, default=0, null=True)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Which_Site_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kapas.Site')),
            ],
        ),
    ]
