# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kapas', '0004_dailysitereading'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeterReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_use', models.FloatField(blank=True, default=0, null=True)),
                ('reading_of', models.PositiveIntegerField(choices=[(0, b'Energy'), (1, b'Voltage'), (2, b'Current'), (3, b'Power')], default=0)),
                ('unit_consumption', models.FloatField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('which_Site_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kapas.Site')),
            ],
        ),
    ]
